In [1]:
import numpy as np

In [3]:
proportions = np.random.dirichlet([1, 1, 1])
proportions.sum()

0.9999999999999999

In [2]:
a = np.array([0.1, 0.2, 0.3, 0.4])
a

array([0.1, 0.2, 0.3, 0.4])

In [4]:
b = np.cumsum(a)
b

array([0.1, 0.3, 0.6, 1. ])

In [8]:
a = [1]
b = [2]
a+b

[1, 2]

In [7]:
(np.cumsum(a)*10).astype(int)

array([ 1,  3,  6, 10])